# this is circle CI configuration file

version: 2.1
jobs:
  build-test:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/calculator
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm run test

workflows:
  version: 2
  calc-workflow:
    jobs:
      - build-test