# configure ocis and run one test

version: 2.1

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:2023.04.2

jobs:
  build-ocis:
    executor: ubuntu-executor
    working_directory: ~/www
    steps:
      - run:
          name: Install Go
          command: |
            sudo apt-get update
            wget https://dl.google.com/go/go1.20.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.20.linux-amd64.tar.gz
            export PATH="/usr/local/go/bin:$PATH"
            go version

      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.gz -o node.tar.gz
            tar -xzf node.tar.gz
            sudo mv node-v18.15.0-linux-x64 /usr/local/node
            sudo ln -sf /usr/local/node/bin/node /usr/bin/node
            sudo ln -sf /usr/local/node/bin/npm /usr/bin/npm
            sudo ln -sf /usr/local/node/bin/npx /usr/bin/npx
            npm install -g pnpm@latest
            node --version
            npm --version
            pnpm --version

      - run:
          name: Install PHP 8
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install -y php8.0
            sudo apt-get install -y php8.0-simplexml php8.0-curl php8.0-mbstring
            sudo apt-get install -y php8.0-ldap

      - run:
          name: Clone ocis
          command: |
            git clone https://github.com/owncloud/ocis.git

      - run:
          name: Generate and Build ocis
          command: |
            pwd
            ls
            cd ocis
            make clean
            make generate
            cd ocis
            make clean
            make build
            ls

      - run:
          name: Run ocis
          command: |
            pwd
            cd ocis
            IDM_ADMIN_PASSWORD=admin ocis/bin/ocis init --insecure true
            OCIS_INSECURE=true PROXY_ENABLE_BASIC_AUTH=true ocis/bin/ocis server
          background: true

      - run:
          name: Wait for ocis server
          command: |
            while ! curl -s -k https://localhost:9200 > /dev/null; do sleep 1; done

      # Install Composer
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php -- --install-dir=$HOME --filename=composer
            echo 'export PATH="$HOME:$PATH"' >> $BASH_ENV && source $BASH_ENV
            composer --version

      - run:
          name: Run OCIS local API Tests
          command: |
            cd ocis
            TEST_SERVER_URL=https://localhost:9200  TEST_WITH_GRAPH_API=true  make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiGraph/createGroup.feature:12

workflows:
  acceptance-tests:
    jobs:
      - build-ocis
