# this is circle CI configuration file

version: 2.0

jobs:
  jest-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
        name: jest-tests
        command: |
          npm install
          npm run jest

workflows:
  calc-workflow:
    jobs:
      - jest-test