# this is circle CI configuration file

version: 2.1

jobs:
  jest-test:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/calculator
    steps:
      - checkout
      - run: |
            name: Install Dependencies
            npm install
      - run: |
            name: Run unit tests
            npm run test

workflows:
  calc-workflow:
    jobs:
      - jest-test