# this is circle CI configuration file

version: 2.1
commands:
  Install Dependencies:
    steps:
      - run:
          name: Install Packages
          command: |
            npm install

jobs:
  build-test:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/calculator
    steps:
      - checkout
      - Install Dependencies:
      - run:
          name: Run tests
          command: |
            npm run test

  deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Deploy your application
          command: |
            npm run deploy

workflows:
  calc-workflow:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - pull-request
                - master

      - deploy:
          filters:
            branches:
              only:
                - master
