# this is circle CI configuration file

version: 2.0

jobs:
  jest-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - name: jest jest-test
      - run: |
          npm install
          npm run jest

workflows:
  calc-workflow:
    jobs:
      - jest-test
