# this is circle CI configuration file

version: 2.1

jobs:
  jest-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: |
          name: Run test Tests
          command: |
            npm install
            npm run jest

workflows:
  calc-workflow:
    jobs:
      - jest-test