version: 2.1
jobs:
  build:
    docker:
      - image: owncloud/ocis:latest
    steps:
      - run:
          name: Wait for ocis server
          command: |
            timeout 30 bash -c 'while ! curl -k -s https://localhost:9200; do sleep 1; done'
            echo "Found"
